### ISSUE TITLE
Changing shape

### ISSUE THREAD

**Issue by elizeng** [esteinig/netview#1]
Thank you for the well explained tutorial!
I am wondering if there is any way to change the shape of individuals for different populations?
Also, can a legend be plotted? The d3.legend doesnt seem to work when set to true.

**Comment by esteinig** [comment]
You can change the shape for populations using the network object (g) returned from `netview` without networkD3. Use a vector of shapes corresponding to each node and its population (as in your data frame) in `vertex.shape`:

`plot(g, vertex.shape=c("triangle", "triangle", "rectangle", ...), vertex.label=NA, ...)`

For more information see [this question on Stackoverflow](http://stackoverflow.com/questions/7429162/how-to-use-igraph-vertex-shape-functionality).

The legend in networkD3 corresponds to the `Group` in your data frame - it works for the example data, have a look if it does for you? 

Another nice library for plotting graphs is [ggnet2](https://briatte.github.io/ggnet/), you can import the `igraph` objects from NetView.
