### ISSUE TITLE
Hiccup w/ NetView Install

### ISSUE THREAD

**Issue by collinstorlie** [esteinig/netview#2]
Attempting install in via R studio, R version and OS info:

R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

Followed instructions on main page of GitHub repo.

Install failed w/ the below error for each of the following packages: proxy, FNN, deldir, gtable, scales, lazyeval, tibble, gtools, gdata, caTools, htmltools.

"Downloading GitHub repo esteinig/netview@master
from URL https://api.github.com/repos/esteinig/netview/zipball/master
Installing netview
"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/jc152199/AppData/Local/Temp/RtmpUZXCD7/devtoolsa9c5b86130/esteinig-netview-e163b45"  \
  --library="C:/Users/jc152199/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'netview' ...
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'htmltools'
ERROR: lazy loading failed for package 'netview'
* removing 'C:/Users/jc152199/Documents/R/win-library/3.3/netview'
Error: Command failed (1)"

After manual install.packages() of all packages in the above list, netview installed successfully.  Don't know exactly what caused this issue, perhaps these packages are sub-dependent packages (depended upon by the dependent packages of netview), which aren't identified as such during install?  Easy fix, put this list of packages on main page with install instructions.

Keep the open-source goodness coming Eike, JCU researchers need help from talented folks such as yourself :-)

Collin Storlie

**Comment by esteinig** [comment]
Thanks Collin, much appreciated! This has been an issue in one of Shannon's tutorials as well, so will leave this open and fix it up over Christmas.

**Comment by esteinig** [comment]
Hey Collin,

as a late fix for this could you try the `installNetview()` function and let me know if it works? I am just restructuring the packet and have the automatic install on my list.

**Comment by collinstorlie** [comment]
Eike,


      I'm happy to provide you feedback about how your new installer works, but I'm a bit busy this arvo. I'll definitely have some time to give this a go later in the week and will let you know how it works out.


Regards,


Collin

__________________________________________________


Dr. Collin Storlie

eResearch Analyst


Queensland Cyber Infrastructure Foundation (QCIF)

eResearch Centre, James Cook University


Address:

James Cook University

eResearch Centre

Building 17, Room 057

Townsville, QLD 4811


Phone:

Office: +61 7 4781 4556

Mobile: +61 4 3754 8692


__________________________________________________


________________________________

**Comment by esteinig** [comment]
Definitely no rush Collin, but very much appreciated. I will fix it at the source but the code for the install function was already ghosting in the packet. Let me give this a proper look before you waste your time testing it, that's my job, really.
